### ISSUE TITLE
Major slowdown in latest revision

### ISSUE THREAD

**Issue by mweyland** [cpavlina/bomtool#2]
bomtool usually took about 5 -- 15 minutes to fulfil the project I'm currently working on. Lately though this has increased to more than 1.5 hours. It seems to wait a very long time while displaying the cart before it proceeds with the next item. I also have the impression that the more parts are in the cart, the longer it waits there. We discussed it in IRC and the most likely culprit was identified to be a slow network connection or digikey being momentarily slow. 

I managed to rule out both of those because if I revert to e.g. revision 005a0bfd2c94c3b7db12377497c72c47b0dd7bc7, things are quick again. I have the suspicion that the problem was introduced in the following revision:

50b7e9199bebe8721ebdb5abe8915ea665f7486a -- Add support for MOQ.

Although I'd have to test more thoroughly before I can confidently say so. I noted that while waiting on the cart screen, the output is:

> --- Attempting to find replacement for LED YELLOW [0805]
> ---- Setting URL
> ---- Entering part number
> ---- Entering quantity
> ---- Adding to cart
> ---- Handling options...
> ----- No options.
> ---- Handling options...
> ----- No options.
> ---- Handling options...
> ----- No options.
> ---- Handling options...
> ----- No options.
> ---- Handling options...
> ----- No options.
> ---- Handling options...
> ----- No options.
> ---- Handling options...
> ----- No options.
> ---- Handling options...
> ----- No options.
> ---- Handling options...
> ----- No options.
> ---- Handling options...
> ----- No options.

I'm running it as follows:

> ./run fulfill --verbose --source-type=kicad --generic --qty=1 --browser=firefox --keep-open /path/to/project | tee bom.txt

Feel free to ask me in IRC for my netlist and/or my database.

**Comment by cpavlina** [comment]
Think I see the issue. What is the part number defined for `LED YELLOW [0805]`?

**Comment by mweyland** [comment]
> LED YELLOW [0805]
> DIST DIGIKEY 475-2560-1-ND
> END

**Comment by cpavlina** [comment]
_This_ is why I still like statically typed languages.

**Comment by mweyland** [comment]
Fixed indeed. Thank you very much!
