### ISSUE TITLE
'# encoding: utf-8' required for Ruby 1.9

### ISSUE THREAD

**Issue by mweyland** [cpavlina/bomtool#3]
Running revision a2996fb91ffcc54b847acff3c19f09ef08db957e on a current Linux Mint Rafaela 7.2 leads to the following error:

```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /usr/src/bomtool/lib/bomtool/exporter.rb:134: invalid multibyte char (US-ASCII) (SyntaxError)
/usr/src/bomtool/lib/bomtool/exporter.rb:134: invalid multibyte char (US-ASCII)
/usr/src/bomtool/lib/bomtool/exporter.rb:134: syntax error, unexpected $end, expecting keyword_end
      value.gsub! '≤', '\\ensuremath{\\leq}'
                     ^
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/src/bomtool/lib/bomtool.rb:4:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from ./bin/bomtool:3:in `<main>'
```
Inserting `# encoding: utf-8` at the top of `exporter.rb` fixes this. My understanding is that this is only needed for Ruby versions below 2.0. I am not sure if `gem install magic_encoding` is needed for this to work.

**Comment by cpavlina** [comment]
Ruby 1.9 might have a few other Unicode-related issues as well; 2.0 handles Unicode more smoothly. I'll have a closer look at it than just adding encoding headers (though yes, that's all you need to do in 1.9 to get UTF-8 string literals AFAIK).

Shame Mint is still suck on 1.9 - even _Debian_ has upgraded to 2.1, and Ubuntu has had ≥2.0 for the last two releases. Looks like it didn't make it into the last LTS, though.
